// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: xai/api/v1/usage.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Records the cost associated with a sampling request (both chat and sample
// endpoints).
type SamplingUsage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of text completion tokens generated across all choices
	// (in case of n>1).
	CompletionTokens int32 `protobuf:"varint,1,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	// Total number of reasoning tokens generated across all choices.
	ReasoningTokens int32 `protobuf:"varint,6,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	// Total number of prompt tokens (both text and images).
	PromptTokens int32 `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	// Total number of tokens (prompt + completion).
	TotalTokens int32 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	// Total number of (uncached) text tokens in the prompt.
	PromptTextTokens int32 `protobuf:"varint,4,opt,name=prompt_text_tokens,json=promptTextTokens,proto3" json:"prompt_text_tokens,omitempty"`
	// Total number of cached text tokens in the prompt.
	CachedPromptTextTokens int32 `protobuf:"varint,7,opt,name=cached_prompt_text_tokens,json=cachedPromptTextTokens,proto3" json:"cached_prompt_text_tokens,omitempty"`
	// Total number of image tokens in the prompt.
	PromptImageTokens int32 `protobuf:"varint,5,opt,name=prompt_image_tokens,json=promptImageTokens,proto3" json:"prompt_image_tokens,omitempty"`
	// Number of individual live search sources used.
	// Only applicable when live search is enabled.
	// e.g. If a live search query returns citations from both X and Web and news sources, this will be 3.
	// If it returns citations from only X, this will be 1.
	NumSourcesUsed int32 `protobuf:"varint,8,opt,name=num_sources_used,json=numSourcesUsed,proto3" json:"num_sources_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SamplingUsage) Reset() {
	*x = SamplingUsage{}
	mi := &file_xai_api_v1_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingUsage) ProtoMessage() {}

func (x *SamplingUsage) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingUsage.ProtoReflect.Descriptor instead.
func (*SamplingUsage) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_usage_proto_rawDescGZIP(), []int{0}
}

func (x *SamplingUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *SamplingUsage) GetReasoningTokens() int32 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *SamplingUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *SamplingUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *SamplingUsage) GetPromptTextTokens() int32 {
	if x != nil {
		return x.PromptTextTokens
	}
	return 0
}

func (x *SamplingUsage) GetCachedPromptTextTokens() int32 {
	if x != nil {
		return x.CachedPromptTextTokens
	}
	return 0
}

func (x *SamplingUsage) GetPromptImageTokens() int32 {
	if x != nil {
		return x.PromptImageTokens
	}
	return 0
}

func (x *SamplingUsage) GetNumSourcesUsed() int32 {
	if x != nil {
		return x.NumSourcesUsed
	}
	return 0
}

// Usage of embedding models.
type EmbeddingUsage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of feature vectors produced from text inputs.
	NumTextEmbeddings int32 `protobuf:"varint,1,opt,name=num_text_embeddings,json=numTextEmbeddings,proto3" json:"num_text_embeddings,omitempty"`
	// The number of feature vectors produced from image inputs.
	NumImageEmbeddings int32 `protobuf:"varint,2,opt,name=num_image_embeddings,json=numImageEmbeddings,proto3" json:"num_image_embeddings,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EmbeddingUsage) Reset() {
	*x = EmbeddingUsage{}
	mi := &file_xai_api_v1_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingUsage) ProtoMessage() {}

func (x *EmbeddingUsage) ProtoReflect() protoreflect.Message {
	mi := &file_xai_api_v1_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingUsage.ProtoReflect.Descriptor instead.
func (*EmbeddingUsage) Descriptor() ([]byte, []int) {
	return file_xai_api_v1_usage_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingUsage) GetNumTextEmbeddings() int32 {
	if x != nil {
		return x.NumTextEmbeddings
	}
	return 0
}

func (x *EmbeddingUsage) GetNumImageEmbeddings() int32 {
	if x != nil {
		return x.NumImageEmbeddings
	}
	return 0
}

var File_xai_api_v1_usage_proto protoreflect.FileDescriptor

const file_xai_api_v1_usage_proto_rawDesc = "" +
	"\n" +
	"\x16xai/api/v1/usage.proto\x12\axai_api\"\xf2\x02\n" +
	"\rSamplingUsage\x12+\n" +
	"\x11completion_tokens\x18\x01 \x01(\x05R\x10completionTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x06 \x01(\x05R\x0freasoningTokens\x12#\n" +
	"\rprompt_tokens\x18\x02 \x01(\x05R\fpromptTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12,\n" +
	"\x12prompt_text_tokens\x18\x04 \x01(\x05R\x10promptTextTokens\x129\n" +
	"\x19cached_prompt_text_tokens\x18\a \x01(\x05R\x16cachedPromptTextTokens\x12.\n" +
	"\x13prompt_image_tokens\x18\x05 \x01(\x05R\x11promptImageTokens\x12(\n" +
	"\x10num_sources_used\x18\b \x01(\x05R\x0enumSourcesUsed\"r\n" +
	"\x0eEmbeddingUsage\x12.\n" +
	"\x13num_text_embeddings\x18\x01 \x01(\x05R\x11numTextEmbeddings\x120\n" +
	"\x14num_image_embeddings\x18\x02 \x01(\x05R\x12numImageEmbeddingsB1Z/github.com/Maniacal/go-xai-sdk/proto/xai/api/v1b\x06proto3"

var (
	file_xai_api_v1_usage_proto_rawDescOnce sync.Once
	file_xai_api_v1_usage_proto_rawDescData []byte
)

func file_xai_api_v1_usage_proto_rawDescGZIP() []byte {
	file_xai_api_v1_usage_proto_rawDescOnce.Do(func() {
		file_xai_api_v1_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xai_api_v1_usage_proto_rawDesc), len(file_xai_api_v1_usage_proto_rawDesc)))
	})
	return file_xai_api_v1_usage_proto_rawDescData
}

var file_xai_api_v1_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xai_api_v1_usage_proto_goTypes = []any{
	(*SamplingUsage)(nil),  // 0: xai_api.SamplingUsage
	(*EmbeddingUsage)(nil), // 1: xai_api.EmbeddingUsage
}
var file_xai_api_v1_usage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xai_api_v1_usage_proto_init() }
func file_xai_api_v1_usage_proto_init() {
	if File_xai_api_v1_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xai_api_v1_usage_proto_rawDesc), len(file_xai_api_v1_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xai_api_v1_usage_proto_goTypes,
		DependencyIndexes: file_xai_api_v1_usage_proto_depIdxs,
		MessageInfos:      file_xai_api_v1_usage_proto_msgTypes,
	}.Build()
	File_xai_api_v1_usage_proto = out.File
	file_xai_api_v1_usage_proto_goTypes = nil
	file_xai_api_v1_usage_proto_depIdxs = nil
}
